#pragma once

const enum ElementTypeId{
    SPRITE, // SPRITES IN GENERAL
    AUDIO, // ANY AUDIO FILE ( MP3, WAV, ETC.. )
    FOLDER, // ANY FOLDER ON ASSET BROWSER
    SCENE, // ANY SCENE ON ASSET BROWSER
    CPP //CPP COMPONENTS, SCRIPT PRESENT ON PROJECT
}; 