#pragma once
#include "string"
#include "functional"
#include "any"
#include "nlohmann/json.hpp"

struct ISerializable;

struct ExSerializedField{
    std::string fieldName;
    const std::type_info& fieldType;
    void* field_ptr;
    ISerializable* serializable_ptr;
    bool editable;
    std::function<void()> onFieldChanged = nullptr;
    std::function<bool(const std::any&)> setValue = nullptr; // type-erased setter generated by EX_SERIALIZER for field_ptr's own type
    std::function<bool(const nlohmann::json&)> setValueFromJson = nullptr; // same, but committing an already-parsed json payload directly (no std::any round trip)
};